config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"

    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    resources :users

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    get ":id/following", to: "following#index", as: "following"
    get ":id/followers", to: "followers#index", as: "followers"

    resources :account_activations, only: :edit

    resources :password_resets

    resources :microposts, only: [:create, :destroy]

    resources :relationships
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div id="error_explanation">
        <div class="alert alert-danger">
          <%= t(".contains") %><%= pluralize object.errors.count, "error" %>.
        </div>
        <ul>
          <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= paginate @feed_items, theme: "twitter-bootstrap-3" %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: t(".compose_new") %>
  </div>
  <%= f.submit t(".post"), class: "btn btn-primary" %>
  <span class="image">
    <%= f.file_field :image, accept: Settings.micropost.content_type %>
  </span>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= link_to(following_path @user) do %>
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <%= t("shared._stats.following") %>
  <% end %>
  <%= link_to(followers_path @user) do %>
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= t("shared._stats..followers") %>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: Settings.user.size), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t(".view_my_profile"), current_user %></span>
<span><%= pluralize current_user.microposts.count, "micropost" %></span>