config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"

    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    resources :users

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    get ":id/following", to: "following#index", as: "following"
    get ":id/followers", to: "followers#index", as: "followers"

    resources :account_activations, only: :edit

    resources :password_resets

    resources :microposts, only: [:create, :destroy]

    resources :relationships
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".sample_app"), "#", id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("home"), root_path %></li>
        <li><%= link_to t("help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("users.title"), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             <%= t("account.title") %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("account.profile"), current_user %></li>
              <li><%= link_to t("account.setting"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("account.log_out"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("account.login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "share", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>